rng.settings:
  type: config_entity
  label: 'RNG settings'
  mapping:
    identity_types:
      type: sequence
      label: 'Identity types'
      sequence:
        type: string

rng.registration_type.*:
  type: config_entity
  label: 'Registration type'
  mapping:
    label:
      type: label
      label: 'Name'
    id:
      type: string
      label: 'Machine-readable name'
    description:
      type: text
      label: 'Description'

rng.registrant_type.*:
  type: config_entity
  label: 'Registrant type'
  mapping:
    label:
      type: label
      label: 'Name'
    id:
      type: string
      label: 'Machine-readable name'
    description:
      type: text
      label: 'Description'
    label_pattern:
      type: string
      label: 'Fallback default title pattern'

rng.rng_event_type.*.*:
  type: config_entity
  label: 'Event bundle settings'
  mapping:
    id:
      type: string
      label: 'ID'
    entity_type:
      type: string
      label: 'Entity type'
    bundle:
      type: string
      label: 'Bundle'
    mirror_operation_to_event_manage:
      type: string
      label: 'Mirrors another operation grant from the event to event manage.'
    allow_anon_registrants:
      type: boolean
      label: 'Allow anonymous registrants to be created, without requiring an identity.'
    auto_sync_registrants:
      type: boolean
      label: 'Automatically sync field data with matching field names between registrant and its identity.'
    auto_attach_users:
      type: boolean
      label: 'Automatically attach anonymous registrations to existing users if email address matches.'
    registrant_email_field:
      type: string
      label: 'Machine name of email field on registrant to look up on user account.'
    event_start_date_field:
      type: string
      label: 'Machine name of event start date field on event entity.'
    event_end_date_field:
      type: string
      label: 'Machine name of event end date field. Uses end_value if exists.'
    fields:
      type: sequence
      label: 'Fields to add to event bundles.'
      sequence:
        type: string
    custom_rules:
      type: boolean
      label: 'Allow event managers to customise default rules.'
    default_registrant:
      type: string
      label: 'Registrant type for new registrants associated with this event type.'
    people_types:
      type: sequence
      label: 'Types of people types allowed to be associated with this event type.'
      sequence:
        type: rng_event_type_people_type
    default_messages:
      type: sequence
      label: 'Default messages for this event type.'
      sequence:
        type: rng_event_type_default_message

condition.plugin.rng_user_role:
  type: condition.plugin.user_role

condition.plugin.rng_registration_identity:
  type: condition.plugin

condition.plugin.rng_event_operation:
  type: condition.plugin
  mapping:
    operations:
      type: mapping
      mapping:
        'manage event':
          type: boolean
          label: 'Manage event'

action.configuration.registration_operations:
  type: mapping
  label: 'Set registration operation access configuration.'
  mapping:
    operations:
      type: mapping
      mapping:
        create:
          type: boolean
          label: 'Create'
        view:
          type: boolean
          label: 'View'
        update:
          type: boolean
          label: 'Update'
        delete:
          type: boolean
          label: 'Delete'

rng.rule.*.*.*:
  type: config_entity
  label: 'A collection of default rules'
  mapping:
    id:
      type: string
      label: 'ID'
    entity_type:
      type: string
      label: 'Entity type'
    bundle:
      type: string
      label: 'Bundle'
    machine_name:
      type: string
      label: 'Machine name'
    trigger:
      type: string
      label: 'Trigger'
    conditions:
      type: sequence
      label: 'Conditions'
      sequence:
        type: condition.plugin.[id]
        label: 'Condition'
    client:
      type: string
      label: 'Client'
    format:
      type: string
      label: 'Format'
    pager_settings:
      type: string
      label: 'Pager settings'
    api_key_settings:
      type: string
      label: 'API key'
    parameters:
      type: string
      label: 'Parameters'
    actions:
      type: sequence
      label: 'Actions'
      sequence:
        label: 'Action'
        type: rng_action.plugin

user.role.*.third_party.rng:
  type: mapping
  mapping:
    condition_rng_role:
      type: boolean
      label: 'Expose this rule to RNG role condition plugin'
